// categorys
export const GET_ALL_CATEGORY = "GET_ALL_CATEGORY";
export const GET_ONE_CATEGORY = "GET_ONE_CATEGORY";
export const CREATE_CATEGORY = "CREATE_CATEGORY";
export const DELETE_CATEGORY = "DELETE_CATEGORY";

export const GET_ALL_COUPONS = "GET_ALL_COUPONS";
export const CREATE_COUPON = "CREATE_COUPON";
export const DELETE_COUPON = "DELETE_COUPON";
export const GET_ONE_COUPON = "GET_ONE_COUPON";
export const UPDATE_COUPON = "UPDATE_COUPON";

export const GET_SUB_CATEGORY = "GET_ALL_SUB_CATEGORY";
export const CREATE_SUB_CATEGORY = "CREATE_SUB_CATEGORY";

// brands
export const GET_ALL_BRANDS = "GET_ALL_BRANDS";
export const GET_ONE_BRAND = "GET_ONE_BRAND";
export const CREATE_BRAND = "CREATE_BRAND";
export const DELETE_BRAND = "DELETE_BRAND";

// products
export const GET_ALL_PRODUCTS = "GET_ALL_PRODUCTS";
export const GET_ONE_PRODUCT = "GET_ONE_PRODUCT";
export const CREATE_PRODUCT = "CREATE_PRODUCT";
export const DELETE_PRODUCT = "DELETE_PRODUCT";
export const UPDATE_PRODUCT = "UPDATE_PRODUCT";
export const GET_ALL_PRODUCT_CATEGORY = "GET_ALL_PRODUCT_CATEGORY";
export const GET_ALL_PRODUCT_BRAND = "GET_ALL_PRODUCT_BRAND";
export const GET_ALL_PRODUCTS_SEARSH = "GET_ALL_PRODUCTS_SEARSH";
export const GET_ALL_PRODUCTS_CONTAINER1 = "GET_ALL_PRODUCTS_CONTAINER1";
export const GET_ALL_PRODUCTS_CONTAINER2 = "GET_ALL_PRODUCTS_CONTAINER2";

// orders
export const GET_ALL_ORDERS = "GET_ALL_ORDERS";
export const GET_ONE_ORDER = "GET_ONE_ORDER";
export const UPDATE_TO_PAY = "UPDATE_TO_PAY";
export const UPDATE_TO_DELIVERY = "UPDATE_TO_DELIVERY";

// reviews
export const GET_ALL_REVIEWS = "GET_ALL_REVIEWS";
export const CREATE_REVIEW = "CREATE_REVIEW";
export const UPDATE_REVIEW = "UPDATE_REVIEW";
export const DELETE_REVIEW = "DELETE_REVIEW";

// auth
export const USER_LOGIN = "USER_LOGIN";
export const USER_REGISTER = "USER_REGISTER";
export const FORGET_PASSWORD = "FORGET_PASSWORD";
export const VERIFY_PASSWORD = "VERIFY_PASSWORD";
export const RESET_PASSWORD = "RESET_PASSWORD";
export const GET_LOGGED_USER_DATA = "GET_LOGGED_USER_DATA";
export const UPDATE_LOGGED_USER_DATA = "UPDATE_LOGGED_USER_DATA";
export const UPDATE_LOGGED_USER_PASSWORD = "UPDATE_LOGGED_USER_PASSWORD";

// cart
export const ADD_PRODUCT_TO_CART = "ADD_PRODUCT_TO_CART";
export const GET_USER_CART = "GET_USER_CART";

export const DELETE_USER_CART_ITEM = "DELETE_USER_CART_ITEM";
export const CLEAR_CART = "CLEAR_CART";
// coupon
export const APPLY_COUPON = "APPLY_COUPON";
export const UPDATE_ITEM_QUANTITY = "UPDATE_ITEM_QUANTITY";

// wish list
export const GET_WISH_LIST = "GET_WISH_LIST";
export const CREATE_WISH_LIST = "CREATE_WISH_LIST";
export const DELETE_WISH_LIST = "DELETE_WISH_LIST";

// .....
export const USER_INFO = "CREATE_REVIEW";
export const UPDATE_USER_PROFILE = "CREATE_REVIEW";
export const UPDATE_USER_PASSWORD = "CREATE_REVIEW";

export const CREATE_ORDER_CASH = "CREATE_ORDER_CASH";
export const CREATE_ORDER_CARD = "CREATE_ORDER_CARD";

export const GET_ERROR = "GET_ERROR";
